### ISSUE TITLE
Errorhandling if funding is not sufficient 

### ISSUE THREAD

**Issue by arbadacarbaYK** [slaapyhoofd/brrr#13]
Use a wallet (track visible on test slaapyhoofd wallet) with 700sats
Write two cards with a funding amount of each 600 sats 
"Error that BRRing wallets not possible" 
Two wallets are created and visible in the write section

Every generated wallet where one link is missing should be treated as unsuccessful (count) and should not be funded. 
Every generated wallet where the links were all generated but the funding wasnt possible should be treated as unsuccessful (count) and nothing should be shown from them at all. Not for writing nor for printing.

If the funding is missing the wallets resp. payment cannot be rollbacked so a count is needed to know how much cards are missing. 
+Errortext that x wallets couldnt be funded/not all links generated and can be written after this job.

**Comment by slaapyhoofd** [comment]
See [commit](https://github.com/slaapyhoofd/brrr/commit/9129d9a10fc114e1196a442957b2946f8721ff5c)
Instead of complex error handling during the batch, a balance check is performed before batches with filling up enabled.

**Comment by arbadacarbaYK** [comment]
How about not generated links a step before ?

**Comment by slaapyhoofd** [comment]
> How about not generated links a step before ?

It is checked before the entire batch starts, so nothing is created.

**Comment by arbadacarbaYK** [comment]
🚀 Moon
