### ISSUE TITLE
usermanager needed extension not mentioned in docs

### ISSUE THREAD

**Issue by raweber42** [slaapyhoofd/brrr#83]
We spent 5 days figuring out why the tool was not working. Turns out, we were missing the `usermanager` extension. Could you pls add this to the docs?

**Comment by arbadacarbaYK** [comment]
Supersorry ! Slaapy had to leave coding surprisingly and it got outdated at the moment the login got mandatory.
Can you PR to https://github.com/arbadacarbaYK/brrr so we can revive building on it ? I also want to add some things :D Made you collaborateur

**Comment by slaapyhoofd** [comment]
> Slaapy had to leave coding surprisingly

Sleepy as always! Life got the best of me lately, but things are looking up! 

 > We spent 5 days figuring out why the tool was not working. Turns out, we were missing the `usermanager` extension. Could you pls add this to the docs?

Is the usermanager the only problem, or are there other changes with newer version of lnbits?

**Comment by arbadacarbaYK** [comment]
We want to see pics ! :D 
Few things.. its not actually only usermanager, the funding source and login logic / whole API requests have been changed - the login is now needed with a usr-id and all depending api-requests too. 
The url doesnt have the usr-id in it anylonger but full access is given with it inside (then deleted from url). https://legend.lnbits.com/docs

**Comment by raweber42** [comment]
Nice to see you back @slaapyhoofd !

Also, in the interface you ask for the `LNBits read-key`, but actually you need to give it the _admin_ key (at least for me it didn't work otherwise).

**Comment by arbadacarbaYK** [comment]
> Nice to see you back @slaapyhoofd !
> 
> Also, in the interface you ask for the `LNBits read-key`, but actually you need to give it the _admin_ key (at least for me it didn't work otherwise).

If you made it work, can you PR back to here then ?

**Comment by slaapyhoofd** [comment]
> We want to see pics ! :D

Will see you Saterday!

> Few things.. its not actually only usermanager, the funding source and login logic / whole API requests have been changed - the login is now needed with a usr-id and all depending api-requests too.
> The url doesnt have the usr-id in it anylonger but full access is given with it inside (then deleted from url).

Yes some api and extension changes, everything should work again.


> Also, in the interface you ask for the `LNBits read-key`, but actually you need to give it the _admin_ key (at least for me it didn't work otherwise).

I updated the readme and help texts.

**Comment by arbadacarbaYK** [comment]
Will not be there saturday..

Where do you mean its working ? https://nfc-brrr.com/ is not alive anylonger

**Comment by slaapyhoofd** [comment]
> Will not be there saturday..

:-(

> Where do you mean its working ? https://nfc-brrr.com/ is not alive anylonger

https://brrr.slaapyhoofd.nl

**Comment by arbadacarbaYK** [comment]
Extremely awesome that it works again for everyone, boltcards as event - give-aways are imo such a pain for the users to rewrite after the event is over.. ours is still the best solution after all these years ! 🥳😜 Have a nice one on saturday !
